server:
  port: 8081

debug: false

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yeb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      pool-name: DateHirkariCP
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 180000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    timeout: 10000ms
    host: 120.55.69.50
    port: 6379
    database: 1 # 选择哪个库，默认0库
    lettuce:
      pool:
        max-active: 1024 # 最大连接数，默认 8
        max-wait: 10000ms # 最大连接阻塞等待时间，单位毫秒，默认 -1
        max-idle: 200 # 最大空闲连接，默认 8
        min-idle: 5
    # rabbitmq配置
    rabbitmq:
      username: guest  # 用户名
      password: guest       # 密码
      host: 39.102.65.157     # 服务器地址
      port: 5672       # 端口
      publisher-returns: true      # 消息失败回调
      publisher-confirm-type: correlated    # 消息确认回调
  # 热部署
  devtools:
    restart:
      enabled: true
  freemarker:
    cache: false

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.jason.server.pojo
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.jason.sercer.mapper: debug

spring.mvc.pathmatch:
  matching-strategy:
    ANT_PATH_MATCHER
jwt:
  # Jwt存储的请求头
  tokenHeader: Authorization
  # Jwt加密秘钥
  secret: yeb-secret
  # Jwt 的超期限时间（60*60）*24
  expiration: 604800
  # Jwt负载中拿到开头
  tokenHead: Bearer
